GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/601161112195be14fd235fbc


###

DELETE http://localhost:3001/api/persons/6015049916dc7c2eafe7ac3c

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name":"mudit",
    "number":"24323121"
    
}

###

PUT http://localhost:3001/api/persons/600e34dcc6e09b1e71fa8793
Content-Type: application/json

{
    "name":"mudits",
    "number":"243234"
    
}