
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"Okami",
    "author":"Japaneese",
    "url":"www.fitgirl.com",
    "likes":4
}