GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11ZGl0eCIsImlkIjoiNjAzNWM1YjJkMTRlNDYxYTVjOTM4NmQwIiwiaWF0IjoxNjE0MjQ5ODQ2fQ.3I0j3cjG97oJhd_bZS4X-lKba1eac7OoVaWQbGsWWnM

{
    "title":"GOT",
    "author": "Stannis",
    "url": "www.GOT?WIHTCHER.in",
    "likes": 121
}

###

DELETE http://localhost:3003/api/blogs/6031cd58b96ebc10f5902994

###

GET http://localhost:3003/api/blogs/1

###
GET http://localhost:3003/api/users/
###

PUT http://localhost:3003/api/blogs/6031cd58b96ebc10f5902994
Content-Type: application/json

{   
    "title": "Parasite",
    "author": "kim ko jong hoon",
    "url": "www.SouthKorea.in",
    "likes": 12
}
###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username":"Mu",
    "name":"Mudit",
    "password":"abcd21@1"
}

###

POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username":"Muditx",
    "password":"abcd21@1"
}